version: "3"
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    # command: sh -c "npm run dev"
    expose:
      - "8080"
    ports:
      - "0.0.0.0:8080:8080"
